### ISSUE TITLE
Proposition pour que `Justin | Jean de Sailly` devienne drôle

### ISSUE THREAD

**Issue by Tim-ats-d** [prepas-mp2i/prepas-mp2i.github.io#32]
Parce que c'est pas la première fois qu'il est pas marrant peuchère

**Comment by Tim-ats-d** [comment]
Ah non je viens de me rendre compte que c'est impossible en fait

**Comment by Tim-ats-d** [comment]
Nan en fait j'ai rien dit

**Comment by Tim-ats-d** [comment]
Le frein de `Justin | Jean de Sailly` vient de se rompre, merci de ne pas vous moquez

**Comment by Tim-ats-d** [comment]
L'opération visant a remplacé le frein de `Justin | Jean de Sailly` par une prothèse en plastique a été conclu avec succès

**Comment by Tim-ats-d** [comment]
L'opération visant a remplacer le frein de `Justin | Jean de Sailly` par une prothèse en plastique a été conclu avec succès

**Comment by Tim-ats-d** [comment]
Merci de votre compréhension

**Comment by Tim-ats-d** [comment]
L'opération visant a remplacer le frein de Justin | Jean de Sailly par une prothèse en plastique a été conclu avec succès

**Comment by orjawell** [comment]
Si je peux me permettre, venant d'un mec avec une pp mario cursed, c'est osé.

**Comment by Mashilo-FS** [comment]
osef

**Comment by IAMISSAM** [comment]
Félicitation `Justin | Jean de Sailly` pour ce nouveau frein flambant neuf !

**Comment by Loatchi** [comment]
L'issue est làent mais la pull requestent ??? donde esta ? 
(install gentoo)

**Comment by ajayat** [comment]
J'ai bien peur de devoir fermer cette issue car le problème ne peut pas être résolu

**Comment by Tim-ats-d** [comment]
C'est avec tristesse que j'apprends cette nouvelle, bonne soirée.
